import { jsPDF } from "jspdf";
import QRCode from "qrcode";
import type { PaymentRecord } from "@/services/paymentService";

const BRAND_NAME = "SolarGrid Energy Network";
const BRAND_YELLOW = "#FACC15";

/** Best-effort XLM→USD rate lookup. Returns null if unavailable (offline, rate-limited, etc.). */
async function fetchXlmUsdRate(): Promise<number | null> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 4000);
    const res = await fetch(
      "https://api.coingecko.com/api/v3/simple/price?ids=stellar&vs_currencies=usd",
      { signal: controller.signal }
    );
    clearTimeout(timer);
    if (!res.ok) return null;
    const data = await res.json();
    return typeof data?.stellar?.usd === "number" ? data.stellar.usd : null;
  } catch {
    return null;
  }
}

/**
 * Generates a downloadable PDF receipt for a completed payment and triggers
 * the browser download. Includes a QR code linking to the blockchain explorer.
 */
export async function downloadPaymentReceipt(
  record: PaymentRecord,
  explorerUrl: string
): Promise<void> {
  const [usdRate, qrDataUrl] = await Promise.all([
    fetchXlmUsdRate(),
    QRCode.toDataURL(explorerUrl, { margin: 1, width: 160 }),
  ]);

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const marginX = 48;
  let y = 56;

  // Header
  doc.setFontSize(18);
  doc.setTextColor(20, 20, 20);
  doc.text(BRAND_NAME, marginX, y);
  doc.setFontSize(10);
  doc.setTextColor(120, 120, 120);
  doc.text("Payment Receipt", marginX, y + 16);

  doc.setDrawColor(BRAND_YELLOW);
  doc.setLineWidth(2);
  y += 28;
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 32;

  const row = (label: string, value: string) => {
    doc.setFontSize(10);
    doc.setTextColor(130, 130, 130);
    doc.text(label, marginX, y);
    doc.setFontSize(11);
    doc.setTextColor(20, 20, 20);
    doc.text(value, marginX + 160, y);
    y += 24;
  };

  const date = new Date(record.date);
  const usdValue =
    usdRate != null ? `$${(record.amountXlm * usdRate).toFixed(2)} USD` : "N/A";

  row("Receipt Number", record.txHash || "N/A");
  row("Date", date.toLocaleString());
  row("Meter ID", record.meterId);
  row("Amount Paid", `${record.amountXlm.toFixed(4)} XLM (${usdValue})`);
  row("Payment Plan", record.plan);
  row("Energy Provider", BRAND_NAME);

  y += 16;
  if (record.txHash) {
    doc.addImage(qrDataUrl, "PNG", marginX, y, 90, 90);
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text("Scan to view this transaction on the blockchain explorer", marginX + 100, y + 30);
    doc.textWithLink("View on Stellar Explorer", marginX + 100, y + 48, { url: explorerUrl });
    y += 110;
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "This is an automated receipt generated by SolarGrid. No signature required.",
    marginX,
    y + 20
  );

  const safeHash = (record.txHash || "receipt").slice(0, 12);
  doc.save(`solargrid-receipt-${safeHash}.pdf`);
}
